[project]
name = "auto-coin-trader-v2"
version = "0.1.0"
description = ""
authors = [
    {name = "jungwoo.mac",email = "qwlake@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp (>=3.12.0,<4.0.0)",
    "pydantic (>=2.11.5,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
